# Site settings
title: Palm & Vader
email: rikkipalm@users.noreply.github.com
description: "a digital creative agency"
baseurl: ""
url: "http://palmvader.github.io"

# Build settings
markdown: kramdown
permalink: :title